"""Shared Pāli vocabulary lists for transcription and correction scripts."""

# 1. Saṅgha & Monastic Life
SANGHA = [
    "Saṅgha",
    "bhikkhu",
    "bhikkhunī",
    "sāmaṇera",
    "upāsaka",
    "upāsikā",
    "vihāra",
    "dāna",
    "sīla",
    "bhante",
    "āyasmā",
    "thera",
    "mahāthera",
    "puñña",
    "vassa",
    "kaṭhina",
    "nissaya",
    "pavāraṇā",
    "kappiya",
    "apalokana",
    "ñatti",
    "kammavācā",
    "sīmā",
    "kuṭi",
    "piṇḍacāra",
    "cīvara",
    "upajjhāya",
    "ācariya",
    "saddhā",
    "navaka",
    "majjhima",
    "samaṇa",
    "samaṇa-saññā",
    "tathāgata",
    "arahant",
    "anāgāmī",
    "sakadāgāmī",
    "sotāpanna",
    "mahā",
]

# 2. Dhamma, Sutta & Meditation
DHAMMA = [
    "Dhamma",
    "sutta",
    "nikāya",
    "āgama",
    "abhidhamma",
    "pāli",
    "khandha",
    "rūpa",
    "vedanā",
    "saññā",
    "saṅkhāra",
    "viññāṇa",
    "anicca",
    "anattā",
    "dukkha",
    "paṭiccasamuppāda",
    "avijjā",
    "taṇhā",
    "upādāna",
    "upādānakkhandha",
    "kamma",
    "nibbāna",
    "magga",
    "nirodha",
    "ariya",
    "sacca",
    "kilesa",
    "āsava",
    "nīvaraṇa",
    "lobha",
    "dosa",
    "moha",
    "rāga",
    "paṭigha",
    "māna",
    "bhava",
    "jāti",
    "saṃsāra",
    "nāmarūpa",
    "phoṭṭhabba",
    "phassa",
    "vaya-dhamma",
    "brahmavihāra",
    "brahma",
    "mettā",
    "karuṇā",
    "muditā",
    "upekkhā",
    "pāramī",
    "kusala",
    "akusala",
    "paññā",
    "vimutti",
    "satipaṭṭhāna",
    "dhammānupassanā",
    "kāyānupassanā",
    "vedanānupassanā",
    "cittānupassanā",
    "ānāpānasati",
    "ānāpāna",
    "sati",
    "samādhi",
    "bhāvanā",
    "samatha",
    "vipassanā",
    "jhāna",
    "vitakka",
    "vicāra",
    "pīti",
    "sukha",
    "ekaggatā",
    "nimitta",
    "vīriya",
    "khantī",
    "hiri",
    "ottappa",
    "bojjhaṅga",
    "indriya",
    "bala",
    "padhāna",
    "arūpa",
    "asubha",
    "maraṇassati",
    "thīnamiddha",
    "uddhacca",
    "kukkucca",
    "vicikicchā",
    "passaddhi",
    "sampajañña",
    "suññatā",
    "tilakkhaṇa",
    "idappaccayatā",
    "adhiṭṭhāna",
    "upacāra",
    "appanā",
    "āyatana",
    "upādāya",
    "aññā",
    "sammā",
    "saṅkappa",
    "diṭṭhi",
    "vācā",
    "vāyāma",
    "ājīva",
    "lokavidū",
    "cetanā",
    "rūpa kalāpa",
    "papañca",
    "paccaya",
    "ehipassiko",
    "viññāṇapeta",
    "saññā vedayita nirodha",
]

# 3. Vinaya & Discipline
VINAYA = [
    "Vinaya",
    "pāṭimokkha",
    "uposatha",
    "pārājika",
    "saṅghādisesa",
    "aniyata",
    "nissaggiya",
    "pācittiya",
    "pāṭidesanīya",
    "sekhiya",
    "adhikaraṇasamatha",
    "adhikaraṇa",
    "apatti",
    "thullaccaya",
    "dukkaṭa",
    "dubbhāsita",
    "antaravāsaka",
    "uttarāsaṅga",
    "saṅghāṭi",
    "patta",
    "vikappana",
    "desanā",
    "upasampadā",
    "pabbajjā",
    "sikkhamānā",
    "puñña",
    "apuñña",
    "āneñja",
]

# 4. Extended Buddhist Terms & Titles
EXTENDED_TERMS = [
    "Noble Eightfold Path",
    "Majjhima Nikāya",
    "Sutta-piṭaka",
    "Saṁyutta Nikāya",
    "Aṅguttara Nikāya",
    "Dīgha Nikāya",
    "five aggregates",
    "sutta class",
    "Sayādaw",
    "Aṅguttara",
    "Pa-Auk",
    "Byron Katie",
    "adhisīla",
]

# 5. Places & Monasteries
PLACES = [
    "Wat Nong Pah Pong",
    "Sasanarakkha",
    "Sasanarakkha Buddhist Sanctuary",
    "SBS",
    "Luddhara",
    "Amaravati",
    "Chithurst",
    "Bodhinyana",
]

# 6. Famous Teachers (Global)
FAMOUS_TEACHERS = [
    "Goenka",
    "Ajahn Thanissaro",
    "Pa-Auk Sayadaw",
    "Bhikkhu Anālayo",
    "Bhikkhu Bodhi",
    "Bhikkhu Sujato",
    "Ajahn Chah",
    "SuttaCentral",
    "Bhante Aggacitta",
    "Bhante Ariyadhammika",
    "Richard Gombrich",
    "Dhammajī",
    "Jinasiri",
]

# 7. Monastic Names (Sasanarakkha)
MONASTICS = [
    "Aggadhamma",
    "Amaradhammika",
    "Appamādadhammika",
    "Ariyananda",
    "Balacitta",
    "Bodhicitta",
    "Bodhirasa",
    "Candana",
    "Candavamso",
    "Cāgadhammika",
    "Chandasota",
    "Devamitta",
    "Dhammajāto",
    "Dhammananda",
    "Dhammasudassī",
    "Guttacitta",
    "Guttapala",
    "Jayadhammika",
    "Jāragro",
    "Kappadhammika",
    "Karuṇāpañño",
    "Khantidhammika",
    "Khaymainda",
    "Khemadhammika",
    "Kittisobhana",
    "Kumāra",
    "Kumarra",
    "Kusala",
    "Kusalacāra",
    "Maṅgaladhammika",
    "Mahāñāno",
    "Meghacitta",
    "Nanda",
    "Nandaka",
    "Nārada",
    "Nirodha",
    "Nirodhadhammika",
    "Ñāṇadhammika",
    "Pamodadhammika",
    "Paññādhammika",
    "Pāladhammika",
    "Puññadhammika",
    "Rāhula",
    "Sallekho",
    "Sambodhi",
    "Sampajaññacitta",
    "Santidhammika",
    "Saṅgāmaji",
    "Sobhanavaṁsa",
    "Subharo",
    "Sudanto",
    "Sudhīra",
    "Sugathasiri",
    "Sumana",
    "Thawbita",
    "Ṭhānuttamo",
    "Ṭhitavijjo",
    "Upālidhammika",
    "Upasama",
    "Upekkhādhammika",
    "Uṭṭhānadhammika",
    "Vimuttadhammika",
    "Virāgadhammika",
    "Visuddha",
    "Viveka",
    "Yogadhammika",
]

# 8. Common Sutta Terms
SUTTA_TERMS = [
    "Indriyasaṃvara",
    "Indriya Saṃvara",
    "Upasamanussati",
    "Sīlabbataparāmāsa",
    "Jarāmaraṇa",
    "Sasaṅkhāraniggahavāritavata",
    "Abyāpajjādhimutta",
    "Sutta-jhāna",
    "Yonisomanasikāra",
    "Saṃyojana",
    "Anusaya",
    "Nekkhamma",
    "Brahmacariya",
    "Iddhipāda",
    "Sammāppadhāna",
    "Sattabojjhaṅga",
    "Cattāro Satipaṭṭhānā",
    "Paṭisambhidāmagga",
    "sabbakāya",
    "parimukhaṃ satiṃ upaṭṭhapetvā",
    "sato va assasati sato va passasati",
    "Dhammadesanā",
    "pāmojja",
    "kāyasaṅkhāra",
    "pajānāti",
    "sabbakāya-paṭisaṃvedī",
    "assasati",
    "passasati",
    "dīgha",
    "rassa",
    "Cūḷavedalla Sutta",
    "Visuddhimagga",
    "passambhayaṃ",
    "Dhammapada",
    "Sāriputta",
    "Moggallāna",
    "Ānanda"
]
