"""Shared Pāli vocabulary lists for transcription and correction scripts."""

# 1. Saṅgha & Monastic Life
SANGHA = [
    "Saṅgha",
    "bhikkhu",
    "bhikkhunī",
    "sāmaṇera",
    "upāsaka",
    "upāsikā",
    "vihāra",
    "dāna",
    "sīla",
    "bhante",
    "āyasmā",
    "thera",
    "mahāthera",
    "puñña",
    "vassa",
    "kaṭhina",
    "nissaya",
    "pavāraṇā",
    "kappiya",
    "apalokana",
    "ñatti",
    "kammavācā",
    "sīmā",
    "kuṭi",
    "piṇḍacāra",
    "cīvara",
    "upajjhāya",
    "ācariya",
    "saddhā",
    "navaka",
    "majjhima",
    "samaṇa",
    "samaṇa-saññā",
    "tathāgata",
    "arahant",
    "anāgāmī",
    "sakadāgāmī",
    "sotāpanna",
    "mahā",
]

# 2. Dhamma, Sutta & Meditation
DHAMMA = [
    "Dhamma",
    "sutta",
    "nikāya",
    "āgama",
    "abhidhamma",
    "pāli",
    "khandha",
    "rūpa",
    "vedanā",
    "saññā",
    "saṅkhāra",
    "viññāṇa",
    "anicca",
    "anattā",
    "dukkha",
    "paṭiccasamuppāda",
    "avijjā",
    "taṇhā",
    "upādāna",
    "upādānakkhandha",
    "kamma",
    "nibbāna",
    "magga",
    "nirodha",
    "ariya",
    "sacca",
    "kilesa",
    "āsava",
    "nīvaraṇa",
    "lobha",
    "dosa",
    "moha",
    "rāga",
    "paṭigha",
    "māna",
    "asmimāna",
    "bhava",
    "jāti",
    "saṃsāra",
    "nāmarūpa",
    "phoṭṭhabba",
    "phassa",
    "vaya-dhamma",
    "brahmavihāra",
    "brahma",
    "mettā",
    "karuṇā",
    "muditā",
    "upekkhā",
    "pāramī",
    "kusala",
    "akusala",
    "paññā",
    "vimutti",
    "satipaṭṭhāna",
    "dhammānupassanā",
    "kāyānupassanā",
    "vedanānupassanā",
    "cittānupassanā",
    "ānāpānasati",
    "ānāpāna",
    "sati",
    "samādhi",
    "bhāvanā",
    "samatha",
    "vipassanā",
    "jhāna",
    "vitakka",
    "vicāra",
    "pīti",
    "sukha",
    "ekaggatā",
    "nimitta",
    "vīriya",
    "khantī",
    "hiri",
    "ottappa",
    "bojjhaṅga",
    "indriya",
    "bala",
    "padhāna",
    "arūpa",
    "asubha",
    "maraṇassati",
    "thīnamiddha",
    "uddhacca",
    "kukkucca",
    "vicikicchā",
    "passaddhi",
    "sampajañña",
    "suññatā",
    "tilakkhaṇa",
    "idappaccayatā",
    "adhiṭṭhāna",
    "upacāra",
    "appanā",
    "āyatana",
    "upādāya",
    "aññā",
    "sammā",
    "saṅkappa",
    "diṭṭhi",
    "vācā",
    "vāyāma",
    "ājīva",
    "lokavidū",
    "cetanā",
    "rūpa kalāpa",
    "papañca",
    "paccaya",
    "ehipassiko",
    "viññāṇapeta",
    "saññā vedayita nirodha",
    "catumadhura",
    "pañcadvāra",
    "niggahīta",
]

# 3. Vinaya & Discipline
VINAYA = [
    "Vinaya",
    "pāṭimokkha",
    "uposatha",
    "pārājika",
    "saṅghādisesa",
    "aniyata",
    "nissaggiya",
    "pācittiya",
    "pāṭidesanīya",
    "sekhiya",
    "adhikaraṇasamatha",
    "adhikaraṇa",
    "apatti",
    "thullaccaya",
    "dukkaṭa",
    "dubbhāsita",
    "antaravāsaka",
    "uttarāsaṅga",
    "saṅghāṭi",
    "patta",
    "vikappana",
    "desanā",
    "upasampadā",
    "pabbajjā",
    "sikkhamānā",
    "puñña",
    "apuñña",
    "āneñja",
]

# 4. Extended Buddhist Terms & Titles
EXTENDED_TERMS = [
    "Noble Eightfold Path",
    "Majjhima Nikāya",
    "Sutta-piṭaka",
    "Saṁyutta Nikāya",
    "Aṅguttara Nikāya",
    "Dīgha Nikāya",
    "five aggregates",
    "sutta class",
    "Sayādaw",
    "Aṅguttara",
    "Pa-Auk",
    "Byron Katie",
    "adhisīla",
]

# 5. Places & Monasteries
PLACES = [
    "Wat Nong Pah Pong",
    "Sasanarakkha",
    "Sasanarakkha Buddhist Sanctuary",
    "SBS",
    "Luddhara",
    "Amaravati",
    "Chithurst",
    "Bodhinyana",
]

# 6. Famous Teachers (Global)
FAMOUS_TEACHERS = [
    "Goenka",
    "Ajahn Thanissaro",
    "Pa-Auk Sayadaw",
    "Bhikkhu Anālayo",
    "Bhikkhu Bodhi",
    "Bhikkhu Sujato",
    "Ajahn Chah",
    "SuttaCentral",
    "Bhante Aggacitta",
    "Bhante Ariyadhammika",
    "Richard Gombrich",
    "Dhammajī",
    "Jinasiri",
]

# 7. Monastic Names (Sasanarakkha)
MONASTICS = [
    "Aggadhamma",
    "Amaradhammika",
    "Appamādadhammika",
    "Ariyananda",
    "Balacitta",
    "Bodhicitta",
    "Bodhirasa",
    "Candana",
    "Candavamso",
    "Cāgadhammika",
    "Chandasota",
    "Devamitta",
    "Dhammajāto",
    "Dhammananda",
    "Dhammasudassī",
    "Guttacitta",
    "Guttapala",
    "Jayadhammika",
    "Jāragro",
    "Kappadhammika",
    "Karuṇāpañño",
    "Khantidhammika",
    "Khaymainda",
    "Khemadhammika",
    "Kittisobhana",
    "Kumāra",
    "Kumarra",
    "Kusala",
    "Kusalacāra",
    "Maṅgaladhammika",
    "Mahāñāno",
    "Meghacitta",
    "Nanda",
    "Nandaka",
    "Nārada",
    "Nirodha",
    "Nirodhadhammika",
    "Ñāṇadhammika",
    "Pamodadhammika",
    "Paññādhammika",
    "Pāladhammika",
    "Puññadhammika",
    "Rāhula",
    "Sallekho",
    "Sambodhi",
    "Sampajaññacitta",
    "Santidhammika",
    "Saṅgāmaji",
    "Sobhanavaṁsa",
    "Subharo",
    "Sudanto",
    "Sudhīra",
    "Sugathasiri",
    "Sumana",
    "Thawbita",
    "Ṭhānuttamo",
    "Ṭhitavijjo",
    "Upālidhammika",
    "Upasama",
    "Upekkhādhammika",
    "Uṭṭhānadhammika",
    "Vimuttadhammika",
    "Virāgadhammika",
    "Visuddha",
    "Viveka",
    "Yogadhammika",
]

# 8. Common Sutta Terms
SUTTA_TERMS = [
    "Indriyasaṃvara",
    "Indriya Saṃvara",
    "Upasamanussati",
    "Sīlabbataparāmāsa",
    "Jarāmaraṇa",
    "Sasaṅkhāraniggahavāritavata",
    "Abyāpajjādhimutta",
    "Sutta-jhāna",
    "Yonisomanasikāra",
    "Saṃyojana",
    "Anusaya",
    "Nekkhamma",
    "Brahmacariya",
    "Iddhipāda",
    "Sammāppadhāna",
    "Sattabojjhaṅga",
    "Cattāro Satipaṭṭhānā",
    "Paṭisambhidāmagga",
    "sabbakāya",
    "parimukhaṃ satiṃ upaṭṭhapetvā",
    "sato va assasati sato va passasati",
    "Dhammadesanā",
    "pāmojja",
    "kāyasaṅkhāra",
    "pajānāti",
    "sabbakāya-paṭisaṃvedī",
    "assasati",
    "passasati",
    "dīgha",
    "rassa",
    "Cūḷavedalla Sutta",
    "Visuddhimagga",
    "passambhayaṃ",
    "Dhammapada",
    "Sāriputta",
    "Moggallāna",
    "Ānanda",
]

TAG_POOL_RU = [
    # Core / Tradition
    "#буддизм",
    "#будда",
    "#дхамма",
    "#сангха",
    "#раннийбуддизм",
    "#учениебудды",
    "#палийскийканон",
    "#типитака",
    # Doctrinal concepts
    "#карма",
    "#перерождение",
    "#сансара",
    "#ниббана",
    "#пробуждение",
    "#освобождение",
    "#страдание",
    "#непостоянство",
    "#анатта",
    "#пустота",
    "#мудрость",
    "#прозрение",
    "#маранасати",
    "#четыреблагородныеистины",
    "#восьмеричныйпуть",
    "#сосредоточение",
    "#арахант",
    "#поток",
    # Meditation / Practice
    "#медитация",
    "#джхана",
    "#осознанность",
    "#осознавание",
    "#сатипаттхана",
    "#доброта",
    "#концентрация",
    "#буддийскаямедитация",
    "#практикамедитации",
    "#созерцание",
    "#осознанноедыхание",
    # Mind / Psychology
    "#сознание",
    "#восприятие",
    "#настоящиймомент",
    "#самопознание",
    "#психологиябуддизма",
    # Path / Development
    "#буддийскийпуть",
    "#буддийскаяпрактика",
    "#практика",
    "#духовноеразвитие",
    "#саморазвитие",
    "#духовныепрактики",
    # Broad reach / discoverability
    "#философия",
    "#психология",
    "#духовность",
    "#монах",
    "#буддийскиймонах",
    "#монастырь",
    "#дляначинающих",
    "#внутреннийпокой",
    "#осознаннаяжизнь",
    "#спокойствие",
]

TAG_POOL_EN = [
    "#buddhism",
    "#buddha",
    "#dhamma",
    "#sangha",
    "#earlybuddhism",
    "#buddhasteaching",
    "#palicanon",
    "#tipitaka",
    "#kamma",
    "#rebirth",
    "#samsara",
    "#nibbana",
    "#awakening",
    "#liberation",
    "#suffering",
    "#impermanence",
    "#anatta",
    "#emptiness",
    "#wisdom",
    "#insight",
    "#maranasati",
    "#fournobletruths",
    "#eightfoldpath",
    "#concentration",
    "#arahant",
    "#streamentry",
    "#meditation",
    "#jhana",
    "#mindfulness",
    "#satipatthana",
    "#lovingkindness",
    "#buddhistmeditation",
    "#meditationpractice",
    "#contemplation",
    "#mindfulbreathing",
    "#consciousness",
    "#perception",
    "#presentmoment",
    "#selfknowledge",
    "#buddhistpsychology",
    "#buddhistpath",
    "#buddhistpractice",
    "#practice",
    "#spiritualdevelopment",
    "#selfdevelopment",
    "#spiritualpractices",
    "#philosophy",
    "#psychology",
    "#spirituality",
    "#monk",
    "#buddhistmonk",
    "#monastery",
    "#forbeginners",
    "#innerpeace",
    "#mindfulliving",
    "#calm",
    "#bhikkhu",
    "#devamitto",
]

TAG_SYNC_GROUPS: list[dict[str, list[str]]] = [
    # Pāli ↔ translation pairs — Pāli removed from pool, added by post-process
    {"en": ["dukkha", "suffering"], "ru": ["дуккха", "страдание"]},
    {"en": ["anicca", "impermanence"], "ru": ["аничча", "непостоянство"]},
    {"en": ["vipassana", "insight"], "ru": ["випассана", "прозрение"]},
    {"en": ["samadhi", "concentration"], "ru": ["самадхи", "сосредоточение"]},
    {"en": ["metta", "lovingkindness"], "ru": ["метта", "доброта"]},
    {
        "en": ["anapanasati", "mindfulbreathing"],
        "ru": ["анапанасати", "осознанноедыхание"],
    },
    {
        "en": ["sati", "mindfulness", "awareness"],
        "ru": ["сати", "осознанность", "внимательность"],
    },
    # Synonym / alternate-form pairs — both kept in pool, auto-complete the pair
    {"en": ["nirvana", "nibbana"], "ru": ["нирвана", "ниббана"]},
    {"en": ["awakening", "enlightenment"], "ru": ["пробуждение", "просветление"]},
    {"en": ["rebirth", "reincarnation"], "ru": ["перерождение", "реинкарнация"]},
]
